CREATE TABLE person
(
    id            bigint generated by default as identity PRIMARY KEY,
    name          text,
    gender        character(6),
    creation_date date,
    bank_account_sum bigint
);

CREATE table passport
(
    id   bigint generated by default as identity PRIMARY KEY,
    series int,
    number int,
    person_id bigint
);

CREATE table car
(
    id   bigint generated by default as identity PRIMARY KEY,
    model varchar(255),
    creation_date date,
    person_id bigint
);

CREATE table house
(
    id   bigint generated by default as identity PRIMARY KEY,
    street text,
    number int
);

CREATE table ref_house_person
(
    id   bigint generated by default as identity PRIMARY KEY,
    person_id int,
    house_id int
);
